name: Lint and Publish
on:
  push
  # release:
  #   types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git Version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Install dependencies
        run: npm install
      - name: Running lint
        run: npm run lint
      # - name: Build @ntm/core
      #   run: npx ng build core --prod
      # - name: Publishing core
      #   run: |
      #     cd dist/core
      #     npm version $RELEASE_VERSION
      #     npm config set //registry.npmjs.org/:_authToken=$TOKEN
      #     npm publish
        env:
          TOKEN: ${{secrets.NPM_TOKEN}}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
