name: Build and Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - run: |
          echo $RELEASE_VERSION
        # npm config set //registry.npmjs.org/:_authToken=$TOKEN
        # npm install
        # npx ng build ntm-validators --prod
        # cd dist/ntm-validators
        # npm publish
        env:
          TOKEN: ${{secrets.NPM_TOKEN}}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
