name: Build and Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git Version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set npm configs
        run: npm config set //registry.npmjs.org/:_authToken=$TOKEN
      - name: Install dependencies
        run: npm install
      - name: Set new package Version
        run: |
          cd projects/ntm-validators/ 
          npm version $RELEASE_VERSION
          cd ../../
      - name: Build ntm-validators
        run: npx ng build ntm-validators --prod
      - name: Publishing ntm-validators
        run: |
          cd dist/ntm-validators
          npm publish
        env:
          TOKEN: ${{secrets.NPM_TOKEN}}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
