name: Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npx ng test --code-coverage
      # - name: Upload coverage to Codecov
      # uses: codecov/codecov-action@v1
      # with:
      #   token: ${{ secrets.CODECOV_TOKEN }}
      #   file: ./coverage.xml
      #   files: ./coverage1.xml,./coverage2.xml
      #   directory: ./coverage/reports/
      #   fail_ci_if_error: true
